### Cấu hình datasource Nguyen
spring.application.name=nhom4
server.port=8080
spring.datasource.url=jdbc:sqlserver://localhost:1433;instanceName=SQLEXPRESS;databaseName=TrainingManagement;encrypt=true;trustServerCertificate=true;
spring.datasource.username=nguyen
spring.datasource.password=11223344


### Cấu hình datasource Quoc


### Giữ nguyên, dòng này để đảm bảo rằng dữ liệu khởi tạo sẽ được thực
###thi sau khi datasource đã được cấu hình
spring.jpa.hibernate.ddl-auto=none

### luôn chạy lại schema.sql và data.sql mỗi khi ứng dụng khởi động
# spring.sql.init.mode=always

### dùng để demo dự án, xóa comment để sử dụng, giúp dữ liệu không bị ghi đè theo file data.sql mỗi khi khởi động lại ứng dụng
###Trước khi mở phải comment dòng spring.sql.init.mode=always để tránh lỗi khi chạy ứng dụng
spring.sql.init.mode=never

spring.jpa.defer-datasource-initialization=true

###Bật log sql để kiểm tra câu lệnh SQL được thực thi
spring.jpa.show-sql=true
spring.sql.init.continue-on-error=true