### Cấu hình datasource Nguyen
spring.application.name=nhom4
server.port=8080
spring.datasource.url=jdbc:sqlserver://localhost:1433;instanceName=SQLEXPRESS;databaseName=TrainingManagement;encrypt=true;trustServerCertificate=true;
spring.datasource.username=nguyen
spring.datasource.password=11223344


### Cấu hình datasource Quoc


### Giữ nguyên, dòng này để đảm bảo rằng dữ liệu khởi tạo sẽ được thực
###thi sau khi datasource đã được cấu hình
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true